### PR TITLE
Fix python3 print statements

### PR DESCRIPTION
**Pull request by coreyar**
Closes # for release #.

### CODE REVIEW

**Comment by jonathan-s** [comment]
@agconti +1 for this.

**Comment by agconti** [comment]
@CoreyAR Thanks for contributing! ✨ 💖 

@CoreyAR @jonathan-s since fabric only supports python 2.7, how you guys using this with python 3?

**Comment by coreyar** [comment]
I wasn't using this with Fabric. I used `cookiecutter-django-rest` to scaffold a couple projects and then customize from there.

**Comment by agconti** [comment]
Ahh, and the fabfile prevented you from running it?  @CoreyAR

**Comment by agconti** [comment]
Hey @CoreyAR, @jonathan-s -- with #324 the project was moved entirely to Python 3.6 and the fabfile was removed. ✨ 🎉

Thank you for opening up this issue originally. Closing this now since it was solved by #324

**Pull request closed without merging**
