### PR TITLE
Add migration step to README

### PR DESCRIPTION
**Pull request by ferndot**
Without this step, users are confronted with an error because the users table does not exist in the database.

### CODE REVIEW

**Comment by agconti** [comment]
Hey @joshua-s  thanks for opening a pull request! ✨ 

This is actually already taken care of for you in the [`docker-compose`](https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/docker-compose.yml#L13) file for local development and in the [`Dockerfile`](https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/Dockerfile#L15) for production.

Where did you run into this issue? Were you running the project with `docker-compose up`?

**Comment by ferndot** [comment]
@agconti no problem 😸 

`docker-compose up` certainly does resolve the issue. However, I am concerned that new users who are following the tutorial will not notice this immediately since that step appears after the `createsuperuser` step in the README.

`docker-compose up` could also be run both before and after the `createsuperuser` step, but that seems a bit overkill.

**Comment by agconti** [comment]
@joshua-s thats a great point. 🙏 

I'd rather remove that command from the initialization instructions since its not actually needed to run the app and let developers create a superuser if / when they want to. 

Would you be up for making the changes? I'd love to include you as a contributor.

**Comment by ferndot** [comment]
@agconti I could do that. Would you like there to be a separate section explaining how to run ./manage.py commands since it has the special docker requirements?

**Comment by ferndot** [comment]
?

**Comment by ferndot** [comment]
@agconti there is also an error with the "Initializing the qa sever" command that I will fix.

**Comment by agconti** [comment]
Hey @joshua-s, thanks for the bump! ✨  

Yeah, I'd be great to add small section explaining that you can run management commands with the entrypoint `docker-compose run -rm web`.

thank you for contributing!

**Comment by ferndot** [comment]
@agconti I made those changes

**Comment by agconti** [comment]
@joshua-s  awesome! Merging away! 🎉  ⛵️

**Pull request merged**
